### ISSUE TITLE
Check Ruff config

### ISSUE THREAD

**Issue by engineervix** [engineervix/cookiecutter-wagtail-vix#513]
The configuration has changed. You might need to update like this

```toml
[tool.ruff]
exclude = [".git", "__pycache__", "node_modules", "public", "venv"]
line-length = 120
target-version = "py310"

[tool.ruff.lint]
ignore = ["E203", "E266", "E501"]
select = ["B", "C", "E", "F", "W", "B9"]

[tool.ruff.lint.isort]
known-first-party = ["project"]
section-order = [
  "future",
  "standard-library",
  "third-party",
  "first-party",
  "local-folder",
]

[tool.ruff.lint.pycodestyle]
max-doc-length = 120

[tool.ruff.lint.mccabe]
max-complexity = 10
```

Ref: https://github.com/kevinbowen777/django-start/issues/375
